import p20 from '../../shots/research-stack/manifest.json';
import p21 from '../../shots/list-stack-press/manifest.json';
import p22 from '../../shots/integration-hub/manifest.json';
import p23 from '../../shots/scroll-brake/manifest.json';
import p24 from '../../shots/chart-live/manifest.json';
import p25 from '../../shots/particle-sand-fill/manifest.json';
import p26 from '../../shots/member-grid/manifest.json';
import p27 from '../../shots/ring-annotation/manifest.json';
import p28 from '../../shots/cycle-mechanism/manifest.json';
import p29 from '../../shots/media-before-after/manifest.json';
import p210 from '../../shots/document-write/manifest.json';
import p211 from '../../shots/code-reveal/manifest.json';
import p212 from '../../shots/letterspace-materialize/manifest.json';
import previous0 from '../../shots/text-column-converge/history/1.1.0.manifest.json';
import previous1 from '../../shots/evidence-relay/history/1.1.0.manifest.json';
import previous2 from '../../shots/odometer-roll/history/1.1.0.manifest.json';
import previous3 from '../../shots/paper-title/history/1.1.0.manifest.json';
import previous4 from '../../shots/timeline-travel/history/1.1.0.manifest.json';
import previous5 from '../../shots/word-roll/history/1.1.0.manifest.json';
import previous6 from '../../shots/concept-matrix/history/1.1.0.manifest.json';
import previous7 from '../../shots/source-converge/history/1.1.0.manifest.json';
import previous8 from '../../shots/diagram-cascade/history/1.1.0.manifest.json';
import previous9 from '../../shots/platform-hinge-rise/history/1.1.0.manifest.json';
import previous10 from '../../shots/brace-expand/history/1.1.0.manifest.json';
import previous11 from '../../shots/structure-then-text/history/1.1.0.manifest.json';
import previous12 from '../../shots/pill-slot-cycle/history/1.1.0.manifest.json';
import previous13 from '../../shots/document-conclusions/history/1.1.0.manifest.json';
import previous14 from '../../shots/row-embed/history/1.1.0.manifest.json';
import previous15 from '../../shots/blur-slide/history/1.1.0.manifest.json';
import previous16 from '../../shots/title-to-label/history/1.1.0.manifest.json';
import previous17 from '../../shots/lead-word-assemble/history/1.1.0.manifest.json';
import previous18 from '../../shots/list-reveal/history/1.1.0.manifest.json';
import previous19 from '../../shots/split-text-stagger/history/1.1.0.manifest.json';
import previous20 from '../../shots/card-stack/history/1.1.0.manifest.json';
import history0 from '../../shots/blur-slide/history/1.0.0.manifest.json';
import history1 from '../../shots/paper-title/history/1.0.0.manifest.json';
import history2 from '../../shots/title-to-label/history/1.0.0.manifest.json';
import history3 from '../../shots/lead-word-assemble/history/1.0.0.manifest.json';
import history4 from '../../shots/split-text-stagger/history/1.0.0.manifest.json';
import history5 from '../../shots/brace-expand/history/1.0.0.manifest.json';
import history6 from '../../shots/pill-slot-cycle/history/1.0.0.manifest.json';
import history7 from '../../shots/word-roll/history/1.0.0.manifest.json';
import history8 from '../../shots/text-column-converge/history/1.0.0.manifest.json';
import history9 from '../../shots/evidence-relay/history/1.0.0.manifest.json';
import history10 from '../../shots/list-reveal/history/1.0.0.manifest.json';
import history11 from '../../shots/document-conclusions/history/1.0.0.manifest.json';
import history12 from '../../shots/card-stack/history/1.0.0.manifest.json';
import history13 from '../../shots/row-embed/history/1.0.0.manifest.json';
import history14 from '../../shots/concept-matrix/history/1.0.0.manifest.json';
import history15 from '../../shots/platform-hinge-rise/history/1.0.0.manifest.json';
import history16 from '../../shots/structure-then-text/history/1.0.0.manifest.json';
import history17 from '../../shots/source-converge/history/1.0.0.manifest.json';
import history18 from '../../shots/timeline-travel/history/1.0.0.manifest.json';
import history19 from '../../shots/odometer-roll/history/1.0.0.manifest.json';
import history20 from '../../shots/diagram-cascade/history/1.0.0.manifest.json';
import manifest14 from '../../shots/lead-word-assemble/manifest.json';
import manifest15 from '../../shots/brace-expand/manifest.json';
import manifest16 from '../../shots/pill-slot-cycle/manifest.json';
import manifest17 from '../../shots/word-roll/manifest.json';
import manifest18 from '../../shots/text-column-converge/manifest.json';
import manifest19 from '../../shots/evidence-relay/manifest.json';
import manifest20 from '../../shots/row-embed/manifest.json';
import manifest21 from '../../shots/structure-then-text/manifest.json';
import manifest22 from '../../shots/timeline-travel/manifest.json';
import manifest23 from '../../shots/odometer-roll/manifest.json';
import manifest7 from '../../shots/blur-slide/manifest.json';
import manifest8 from '../../shots/split-text-stagger/manifest.json';
import manifest9 from '../../shots/card-stack/manifest.json';
import manifest10 from '../../shots/concept-matrix/manifest.json';
import manifest11 from '../../shots/platform-hinge-rise/manifest.json';
import manifest12 from '../../shots/source-converge/manifest.json';
import manifest13 from '../../shots/diagram-cascade/manifest.json';
import manifest0 from '../../shots/semantic-default/manifest.json';
import manifest1 from '../../shots/paper-title/manifest.json';
import manifest2 from '../../shots/title-to-label/manifest.json';
import manifest3 from '../../shots/document-conclusions/manifest.json';
import manifest4 from '../../shots/list-reveal/manifest.json';
import manifest5 from '../../shots/compare-reveal/manifest.json';
import manifest6 from '../../shots/network-expand/manifest.json';
import {ShotManifestSchema, type ShotId, type ShotManifest} from '../schemas/shot-recipe';
export const SHOT_CATALOG: readonly ShotManifest[] = [p20, p21, p22, p23, p24, p25, p26, p27, p28, p29, p210, p211, p212, manifest0, manifest1, manifest2, manifest3, manifest4, manifest5, manifest6, manifest7, manifest8, manifest9, manifest10, manifest11, manifest12, manifest13, manifest14, manifest15, manifest16, manifest17, manifest18, manifest19, manifest20, manifest21, manifest22, manifest23].map((value) => ShotManifestSchema.parse(value));
export const LEGACY_SHOT_CATALOG = [history0, history1, history2, history3, history4, history5, history6, history7, history8, history9, history10, history11, history12, history13, history14, history15, history16, history17, history18, history19, history20].map((value) => ShotManifestSchema.parse(value));
export const PREVIOUS_SHOT_CATALOG = [previous0, previous1, previous2, previous3, previous4, previous5, previous6, previous7, previous8, previous9, previous10, previous11, previous12, previous13, previous14, previous15, previous16, previous17, previous18, previous19, previous20].map(value => ShotManifestSchema.parse(value));
export function resolveShot(id: ShotId, version: string): ShotManifest {
  const recipe = [...SHOT_CATALOG, ...PREVIOUS_SHOT_CATALOG, ...LEGACY_SHOT_CATALOG].find((item) => item.id === id && item.version === version);
  if (!recipe) throw new Error(`缺少镜头配方 ${id}@${version}。`);
  return recipe;
}
